# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: app

on:
  workflow_dispatch:
  #schedule:
  #   - cron: '*/12 * * * *'
  #watch:
  #  types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        URL: "https://raw.githubusercontent.com/Sunert/Scripts/master/Task/youth.js"
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          npm install
      - name: '运行 【中青看点】'
        if: env.YOUTH_HEADER
        run: |
          node app.js
          
