name: Github JD-sign bot

on:
    schedule:
        - cron: '32 20 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: Use Node.js 10.x
            uses: actions/setup-node@v1
            with:
              node-version: 10.x
          - name: npm install
            run: |
              npm install
          - name: '运行 【中青看点】'
            run: |
              node Task/youth.js
            env:
                YOUTH_READ: ${{ secrets.YOUTH_READ }}
