name: Github JD-sign bot

on:
    push:
        branches:
            - master
    schedule:
        - cron: '27 20 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: npm install
              run: |
                npm install
            - name: '运行 【中青看点自动阅读】'
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.
