name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * * '
  #watch:
  #  types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      URL: "https://raw.githubusercontent.com/tnanko2019/xmly_speed/master/xmly_speed.py"
      RUNFILE: "xmly_speed.py"
      XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}
      XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }}
      BARK_MACHINE_CODE: ${{ secrets.BARK_MACHINE_CODE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行 【喜马拉雅极速版】'
        #if: env.XMLY_SPEED_COOKIE
        run: |
          python3 app_py.js