# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read
on:
  workflow_dispatch:
  schedule:
     - cron: '*/29 19-23 * * *'
  watch:
    types: started

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node app.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点自动阅读】'
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
