# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: zq_reward

on:
  workflow_dispatch:
  schedule:
     - cron: '12 23,4,12 * * *'
  #watch:
  #  types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
      YOUTH_SHARE_HEADER: ${{ secrets.YOUTH_SHARE_HEADER }}
      YOUTH_SHARE_BODY: ${{ secrets.YOUTH_SHARE_BODY }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.YOUTH_SHARE_BODY
        run: |
          npm install
      - name: '运行 【中青看点_奖励】'
        if: env.YOUTH_SHARE_BODY
        run: |
          node zq_reward.js
          
